module.exports = [
  {
    id: 1,
    title: "Chicken Litti",
    category: "breakfast",
    price: "20 INR",
    img: "images/item-1.jpeg",
    desc: `Litti stuffed with chicken with chicken gravy `,
    name: "Anna Restaurant",
    date: "20 Mar",
    color:"white",
    place:"Update Value",
  },
  {
    id: 2,
    title: "Ghee Litti",
    category: "lunch",
    price: 13.99,
    img: "images/item-2.jpeg",
    desc: `Litti Served with ghee and spicy chokha  `,
    name: "Anna Restaurant",
    date: "2 days ago",
    color:"skyblue",
    place:"Right from",
  },
  {
    id: 3,
    title: "Daal Bati",
    category: "shakes",
    price: 6.99,
    img: "images/item-3.jpeg",
    desc: `Bati made with gram flour and stuffed with daal`,
    name: "Anna Restaurant",
    date: "2 days ago",
    color:"yellow",
    place:"Right from",
  },
  {
    id: 4,
    title: "Chocolate Litti",
    category: "breakfast",
    price: 20.99,
    img: "images/item-4.jpeg",
    desc: `litti stuffed with mixture of chocolate and sattu and served with chocolate Souce `,
    name: "Anna",
    date: "2 days ago",
    color:"brown",
    place:"Times Square",
  },
  {
    id: 5,
    title: "chocolate chai",
    category: "lunch",
    price: 22.99,
    img: "./images/item-5.jpeg",
    desc: `chocolate flavoured chai served with crispy chocolate biscuit`,
    name: "Anna",
    date: "2 days ago",
    color:"white",
    place:"Right from",
  },
  {
    id: 6,
    title: "tondoor chai",
    category: "breakfast",
    price: 8.99,
    img: "./images/item-6.jpeg",
    desc: `chai made with Hot tandoor pot `,
    name: "Anna",
    date: "2 days ago",
    color:"white",
    place:"From India",
  },
  {
    id: 7,
    title: "oreo dream",
    category: "shakes",
    price: 18.99,
    img: "./images/item-7.jpeg",
    desc: `Oreo shake with milk, chocolate and Oreo biscuit`,
    name: "Anna",
    date: "2 days ago",
    color:"brown",
    place:"From India",
  },
  {
    id: 8,
    title: "Plane Litti chokha",
    category: "lunch",
    price: 12.99,
    img: "./images/item-8.jpeg",
    desc: `Simple litti chokha stuffed with sattu and chokha of your choice`,
    name: "Anna",
    date: "2 days ago",
    color:"brown",
    place:"From India",
  },
  {
    id: 9,
    title: "quarantine buddy",
    category: "shakes",
    price: 16.99,
    img: "./images/item-9.jpeg",
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing. It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English.`,
    name: "Anna",
    date: "2 days ago",
    color:"black",
    place:"relate sqaure",
  }
  
];